### ISSUE TITLE
Kullanıcı rol tanımlaması

### ISSUE THREAD

**Issue by cotur** [HereProject/here-webapi#1]
Bilinen hata:
Kullanıcı eklendikten sonra rol tanımlaması yapılmıyor.

**Comment by ebrudgan** [comment]
https://www.gencayyildiz.com/blog/asp-net-core-identity-kullanici-ve-rol-modellerinde-custom-property-tanimlamak-iv/  konuya tam olarak hakim değilim ama böyle bir sayfa buldum. Gözden kaçırılan bir şey olabilir mi?

**Comment by cotur** [comment]
Çözümü biliyorum ya, sadece unutmamak adına buraya yazdım 😅 yarın devam edeceğim.

**Comment by ebrudgan** [comment]
bende sasirmistim zaten ama bug basligi olunca bi katkım olabilir mi
bakayim dedim 😂

11 Kas 2019 Pzt 11:12 ÖS tarihinde Ahmet Çotur <notifications@github.com>
şunu yazdı:
